### ISSUE TITLE
replace crash with _restart

### ISSUE THREAD

**Issue by dragokas** [LuckyServ/sourcemod-plugins#1]
Why
```
ServerCommand("crash");
```
not 
```
ServerCommand("_restart");
```
?

**Comment by LuxLuma** [comment]
Linux don't work with "_restart" gotta do some spooky stuff rikka has showed.

**Comment by dragokas** [comment]
lol, why? I have linux. _restart works.
(L4D1)

**Comment by Timocop** [comment]
_restart is inconsistent. Some games just crash or hang anyways.

**Comment by dragokas** [comment]
Actually, I'm always crash on _restart :))))
So, I use additional crash log parser to delete redundant logs on the next server start.

**Comment by LuckyServ** [comment]
With the crash command, it stops (crashes) the process entirely and returns a non 0 value thus the bash script **srcds_run** launches a new server process. This gets rid of any weird configuration changes / memory leaks the game might've had while running and ensures the best performance for the next game. I'm not sure what _restart actually does. Besides, according to Lux _restart is inconsistent. Case closed.
